grails-app/domain/todolist/ListItem.groovy
package todolist

class ListItem {

    String name
    static belongsTo = [list: TodoList]

    static constraints = {
    }
}

grails-app/domain/todolist/TodoList.groovy
package todolist

class TodoList {

    String name
    static hasMany = [items: ListItem]

    static constraints = {
    }
}

grails-app/controllers/todolist/ListItemController.groovy
package todolist

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class ListItemController {

    ListItemService listItemService
    TodoListService todoListService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond listItemService.list(params), model:[listItemCount: listItemService.count()]
    }

    def show(Long id) {

        ListItem createdItem = listItemService.get(id)
        if(createdItem==null){
          response.sendError(404)
        }else{
          redirect(controller: 'todoList',action: "show",params: [id: createdItem.list.id])
        }
    }

    def create() {
        System.out.println("Params ${params}")
        def model = ['listItem': new ListItem(params),'parent': params['list_id']]
        respond model
    }

    def save(ListItem listItem) {
        if (listItem == null) {
            notFound()
            return
        }

        try {
            listItemService.save(listItem)
        } catch (ValidationException e) {
            respond listItem.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'listItem.label', default: 'ListItem'), listItem.id])
                redirect listItem
            }
            '*' { respond listItem, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond listItemService.get(id)
    }

    def update(ListItem listItem) {
        if (listItem == null) {
            notFound()
            return
        }

        try {
            listItemService.save(listItem)
        } catch (ValidationException e) {
            respond listItem.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'listItem.label', default: 'ListItem'), listItem.id])
                redirect listItem
            }
            '*'{ respond listItem, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        ListItem toDelete = listItemService.get(id)
        println "To Delete: ${toDelete.name} List: ${toDelete.list.id}"
        listItemService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'listItem.label', default: 'ListItem'), id])
                redirect(controller: "todoList", action:"show", method:"GET", id: toDelete.list.id)
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'listItem.label', default: 'ListItem'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/todolist/TodoListController.groovy
package todolist

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class TodoListController {

    TodoListService todoListService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond todoListService.list(params), model:[todoListCount: todoListService.count()]
    }

    def show(Long id) {
        respond todoListService.get(id)
    }

    def create() {
        respond new TodoList(params)
    }

    def save(TodoList todoList) {
        if (todoList == null) {
            notFound()
            return
        }

        try {
            todoListService.save(todoList)
        } catch (ValidationException e) {
            respond todoList.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'todoList.label', default: 'TodoList'), todoList.name])
                redirect todoList
            }
            '*' { respond todoList, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond todoListService.get(id)
    }

    def update(TodoList todoList) {
        if (todoList == null) {
            notFound()
            return
        }

        try {
            todoListService.save(todoList)
        } catch (ValidationException e) {
            respond todoList.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'todoList.label', default: 'TodoList'), todoList.id])
                redirect todoList
            }
            '*'{ respond todoList, [status: OK] }
        }
    }

    def delete(Long id,String name) {
        if (id == null) {
            notFound()
            return
        }

        todoListService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'todoList.label', default: 'TodoList'), name])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'todoList.label', default: 'TodoList'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/todolist/UrlMappings.groovy
package todolist

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(controller:"todoList")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#">
		                <h1>TODO Lists</h1>
                </a>
            </div>
            <div class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
                <ul class="nav navbar-nav navbar-right">
                    <g:pageProperty name="page.nav" />
                </ul>
            </div>
        </div>
    </div>

    <g:layoutBody/>

    <div class="footer" role="contentinfo"></div>

    <div id="spinner" class="spinner" style="display:none;">
        <g:message code="spinner.alt" default="Loading&hellip;"/>
    </div>

    <asset:javascript src="application.js"/>

</body>
</html>

grails-app/views/listItem/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'listItem.label', default: 'List Item')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-listItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" controller="todoList" action="show" params="[id: parent]"><g:message message="Return to ${params['list_name']} List" /></g:link></li>
            </ul>
        </div>
        <div id="create-listItem" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.listItem}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.listItem}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.listItem}" method="POST">
                <g:field type="hidden" name="list" value="${parent}" />
                <f:field bean="${this.listItem}" property="name"/>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/listItem/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'listItem.label', default: 'ListItem')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-listItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link controller="todoList" class="list" action="show" id="${this.listItem.listId}"><g:message message="Back to ${this.listItem.list.name} List" /></g:link></li>
                <li><g:link class="create" action="create"><g:message message="Add List Item" /></g:link></li>
            </ul>
        </div>
        <div id="edit-listItem" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.listItem}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.listItem}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.listItem}" method="PUT">
                <g:hiddenField name="version" value="${this.listItem?.version}" />
                <f:field bean="listItem" property="name"/>                
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/listItem/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'listItem.label', default: 'ListItem')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-listItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-listItem" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${listItemList}" />

            <div class="pagination">
                <g:paginate total="${listItemCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/listItem/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'listItem.label', default: 'ListItem')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-listItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-listItem" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="listItem" property="name"/>
            <g:form resource="${this.listItem}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.listItem}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/todoList/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'todoList.label', default: 'TodoList')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-todoList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-todoList" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.todoList}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.todoList}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.todoList}" method="POST">
                <f:field bean="${this.todoList}" property="name" />
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/todoList/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'todoList.label', default: 'TodoList')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-todoList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="show" params="[id:this.todoList.id]"><g:message message="Return to ${this.todoList.name.capitalize()}" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-todoList" class="content scaffold-edit" role="main">
            <h1><g:message message="${this.todoList.name.capitalize()}" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.todoList}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.todoList}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.todoList}" method="PUT">
                <g:hiddenField name="version" value="${this.todoList?.version}" />
                <fieldset class="form">
                    <f:field bean="todoList" property="name"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/todoList/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'todoList.label', default: 'TODO List')}" />
        <title><g:message message="${entityName}s" /></title>
    </head>
    <body>
        <a href="#list-todoList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-todoList" class="content scaffold-list" role="main">
            <h1><g:message message="${entityName}s" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${todoListList}" properties="['name']"/>

            <div class="pagination">
                <g:paginate total="${todoListCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/todoList/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'todoList.label', default: 'TODO List')}" />
        <g:set var="domainProperties" value="['name']" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-todoList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-todoList" class="content scaffold-show" role="main">
            <h1><f:display bean="todoList" property="name"/></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>

            <table>
              <thead>
                   <tr>
                      <g:each in="${domainProperties}" var="p" status="i">
                          <g:sortableColumn property="${p}" title="${p.capitalize()}" />
                      </g:each>
                  </tr>
              </thead>
              <tbody>
                  <g:each in="${todoList.items}" var="bean" status="i">
                      <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                          <g:each in="${domainProperties}" var="p" status="j">

                              <td><f:display bean="${bean}" property="${p}"  displayStyle="${displayStyle?:'table'}" theme="${theme}"/></td>

                          </g:each>
                          <td>
                            <g:form resource="${bean}" params="[id:bean.id]" method="DELETE">
                              <g:link class="edit" controller="listItem" action="edit" id="${bean.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link> | <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                            </g:form>
                          </td>
                      </tr>
                  </g:each>
                  <tr>
                      <td><g:link controller="listItem" action="create" params="[list_id: todoList.id,list_name: todoList.name]">Add List Item</g:link></td>
                  </tr>
              </tbody>
            </table>

            <g:form resource="${this.todoList}" params="[id:this.todoList.id,name:this.todoList.name]" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.todoList}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>